/**
 * Fixture zone grid for the Gush Dan demo metro.
 *
 * Stands in for Tier A: in production these cells and their static metrics are
 * generated by a monthly cron from GTFS, OSM, CBS and nadlan data and stored in
 * Postgres. Here they are derived deterministically from the H3 index so the
 * app is explorable — and the scoring engine testable — without any pipeline.
 *
 * The numbers are plausible, not real. Nothing here should ever be presented
 * to a user as an actual measurement.
 */

import { cellToBoundary, cellToLatLng, polygonToCells } from "h3-js";

import type { LatLng, Ring } from "@/lib/geo";
import { haversineKm } from "@/lib/geo";
import type { Confidence, Zone, ZoneMetrics } from "@/lib/scoring/types";
import {
  distanceToSpineKm,
  GUSH_DAN_BBOX,
  GUSH_DAN_CENTER,
  municipalityFor,
} from "./geography";
import { noiseFrom, unitFrom } from "./random";

/** §3: resolution 9 — ~0.105 km², ~170 m edge. */
export const ZONE_RESOLUTION = 9;

function clamp01(value: number): number {
  return Math.min(1, Math.max(0, value));
}

function scale100(value: number): number {
  return Math.round(clamp01(value) * 1000) / 10;
}

/**
 * Stand-in for the "only cells containing residential buildings" filter (§3).
 * Israel is mostly empty; without this the grid is full of dead cells.
 */
function isResidential(h3: string, centroid: LatLng): boolean {
  const fromCenter = haversineKm(centroid, GUSH_DAN_CENTER);
  // Density falls off with distance from the metro core, with stable jitter so
  // the built-up area has a ragged edge rather than a perfect disc.
  const probability = clamp01(1.05 - fromCenter / 17);
  return unitFrom(h3, "residential") < probability;
}

function buildMetrics(h3: string, centroid: LatLng): ZoneMetrics {
  const municipality = municipalityFor(centroid);
  const fromCenter = haversineKm(centroid, GUSH_DAN_CENTER);
  const fromSpine = distanceToSpineKm(centroid);

  // --- Transit: dominated by proximity to the high-capacity spine ----------
  const transit = scale100(
    clamp01(0.95 - fromSpine / 4.5) * 0.7 +
      clamp01(0.9 - fromCenter / 12) * 0.3 +
      noiseFrom(h3, "transit") * 0.08,
  );

  // --- Price level: central and coastal is expensive -----------------------
  const coastal = clamp01(1 - (centroid.lng - GUSH_DAN_BBOX.minLng) / 0.12);
  const costIndex = clamp01(
    clamp01(1 - fromCenter / 14) * 0.6 +
      coastal * 0.3 +
      noiseFrom(h3, "cost") * 0.12,
  );
  // ₪18k–₪78k per m², roughly the real Gush Dan spread.
  const cost = Math.round(18000 + costIndex * 60000);

  // --- Parking: the inverse of density, floored near the core --------------
  const parking = scale100(
    clamp01(fromCenter / 9) * 0.65 +
      clamp01(fromSpine / 5) * 0.2 +
      noiseFrom(h3, "parking") * 0.15,
  );

  // --- Socioeconomic index (CBS, 1–10) -------------------------------------
  const socioeconomic =
    Math.round(
      clamp01(
        0.35 +
          clamp01((centroid.lat - GUSH_DAN_BBOX.minLat) / 0.14) * 0.3 +
          coastal * 0.2 +
          noiseFrom(h3, "ses") * 0.25,
      ) *
        9 *
        10,
    ) /
      10 +
    1;

  // --- Safe room likelihood: building-era proxy + shelter proximity --------
  const shelter = scale100(
    municipality.newBuildShare * 0.6 +
      clamp01(fromCenter / 11) * 0.25 +
      noiseFrom(h3, "shelter") * 0.2,
  );

  // --- Shabbat mobility: only some municipalities run Saturday lines -------
  const shabbat = municipality.shabbatService
    ? scale100(clamp01(0.75 - fromSpine / 6) + noiseFrom(h3, "shabbat") * 0.15)
    : scale100(clamp01(noiseFrom(h3, "shabbat") * 0.06));

  // Confidence mirrors the real data situation (§4, §12 risk 2): parking is
  // published as a GIS layer by Tel Aviv and almost nowhere else, so anywhere
  // outside it is a proxy the UI must not present as authoritative.
  const parkingConfidence: Confidence =
    municipality.name === "Tel Aviv-Yafo"
      ? "high"
      : municipality.name === "Ramat Gan" || municipality.name === "Givatayim"
        ? "medium"
        : "low";

  return {
    transit: { value: transit, confidence: "high" },
    // Sale prices aggregated to the cell — a price signal, never rent.
    cost: { value: cost, confidence: "medium" },
    parking: { value: parking, confidence: parkingConfidence },
    socioeconomic: { value: socioeconomic, confidence: "high" },
    shelter: { value: shelter, confidence: "medium" },
    shabbat: { value: shabbat, confidence: "high" },
  };
}

/** Repeat the first vertex at the end, as GeoJSON polygons require. */
function closeRing(ring: Ring): Ring {
  const first = ring[0];
  const last = ring[ring.length - 1];
  if (first[0] === last[0] && first[1] === last[1]) return ring;
  return [...ring, first];
}

export interface ZoneDataset {
  zones: Zone[];
  metrics: Record<string, ZoneMetrics>;
}

function generate(): ZoneDataset {
  const { minLat, maxLat, minLng, maxLng } = GUSH_DAN_BBOX;

  // h3-js takes [lat, lng] pairs unless told the input is GeoJSON.
  const outline: [number, number][] = [
    [minLat, minLng],
    [minLat, maxLng],
    [maxLat, maxLng],
    [maxLat, minLng],
  ];

  const cells = polygonToCells(outline, ZONE_RESOLUTION);

  const zones: Zone[] = [];
  const metrics: Record<string, ZoneMetrics> = {};

  for (const h3 of cells) {
    const [lat, lng] = cellToLatLng(h3);
    const centroid: LatLng = { lat, lng };

    if (!isResidential(h3, centroid)) continue;

    const municipality = municipalityFor(centroid);

    zones.push({
      h3,
      centroid,
      // GeoJSON order ([lng, lat]) so the ring can go straight to MapLibre.
      // `cellToBoundary` returns the six vertices without repeating the first,
      // and GeoJSON requires a closed ring, so close it here.
      boundary: closeRing(cellToBoundary(h3, true) as Ring),
      municipality: municipality.name,
      // Stand-in for the CBS statistical-area join.
      statAreaId: `${municipality.name}-${h3.slice(-3)}`,
    });

    metrics[h3] = buildMetrics(h3, centroid);
  }

  return { zones, metrics };
}

let cached: ZoneDataset | null = null;

/** Generated once per process, then reused. Cheap enough to build in-browser. */
export function getZoneDataset(): ZoneDataset {
  if (!cached) cached = generate();
  return cached;
}
